// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HealthHAResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Lease expiration timestamp in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeaseExpirationUtc { get; set; }
#nullable restore
#else
        public string LeaseExpirationUtc { get; set; }
#endif
        /// <summary>Lease ownership status: Owned or Unowned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeaseState { get; set; }
#nullable restore
#else
        public string LeaseState { get; set; }
#endif
        /// <summary>Instance role: Primary or Standby.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>Current runtime state: Active or Passive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuntimeState { get; set; }
#nullable restore
#else
        public string RuntimeState { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.HealthHAResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.HealthHAResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.HealthHAResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "leaseExpirationUtc", n => { LeaseExpirationUtc = n.GetStringValue(); } },
                { "leaseState", n => { LeaseState = n.GetStringValue(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "runtimeState", n => { RuntimeState = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("leaseExpirationUtc", LeaseExpirationUtc);
            writer.WriteStringValue("leaseState", LeaseState);
            writer.WriteStringValue("role", Role);
            writer.WriteStringValue("runtimeState", RuntimeState);
        }
    }
}
#pragma warning restore CS0618
