// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HealthResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Dependency health check results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Opdl.Sdk.Client.Models.HealthResponse_checks? Checks { get; set; }
#nullable restore
#else
        public global::Opdl.Sdk.Client.Models.HealthResponse_checks Checks { get; set; }
#endif
        /// <summary>Instance identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstanceId { get; set; }
#nullable restore
#else
        public string InstanceId { get; set; }
#endif
        /// <summary>Instance role: Primary or Standby.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>Current runtime state: Active or Passive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuntimeState { get; set; }
#nullable restore
#else
        public string RuntimeState { get; set; }
#endif
        /// <summary>Overall health status: Healthy, Degraded, or Unhealthy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Human-readable process uptime.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uptime { get; set; }
#nullable restore
#else
        public string Uptime { get; set; }
#endif
        /// <summary>Platform runtime version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.HealthResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.HealthResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.HealthResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checks", n => { Checks = n.GetObjectValue<global::Opdl.Sdk.Client.Models.HealthResponse_checks>(global::Opdl.Sdk.Client.Models.HealthResponse_checks.CreateFromDiscriminatorValue); } },
                { "instanceId", n => { InstanceId = n.GetStringValue(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "runtimeState", n => { RuntimeState = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "uptime", n => { Uptime = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Opdl.Sdk.Client.Models.HealthResponse_checks>("checks", Checks);
            writer.WriteStringValue("instanceId", InstanceId);
            writer.WriteStringValue("role", Role);
            writer.WriteStringValue("runtimeState", RuntimeState);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("uptime", Uptime);
            writer.WriteStringValue("version", Version);
        }
    }
}
#pragma warning restore CS0618
