// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RegistrationConflict : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Competing proposals rejected with registration_key_conflict.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Opdl.Sdk.Client.Models.Registration>? Losers { get; set; }
#nullable restore
#else
        public List<global::Opdl.Sdk.Client.Models.Registration> Losers { get; set; }
#endif
        /// <summary>Resolution status of the conflict, resolved when the winner is the deterministic survivor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolutionStatus { get; set; }
#nullable restore
#else
        public string ResolutionStatus { get; set; }
#endif
        /// <summary>Unit identifier shared by all competing proposals.</summary>
        public int? UnitId { get; set; }
        /// <summary>Unit type identifier shared by all competing proposals.</summary>
        public int? UnitType { get; set; }
        /// <summary>The winner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Opdl.Sdk.Client.Models.Registration? Winner { get; set; }
#nullable restore
#else
        public global::Opdl.Sdk.Client.Models.Registration Winner { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.RegistrationConflict"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.RegistrationConflict CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.RegistrationConflict();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "losers", n => { Losers = n.GetCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.Registration>(global::Opdl.Sdk.Client.Models.Registration.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resolution_status", n => { ResolutionStatus = n.GetStringValue(); } },
                { "unit_id", n => { UnitId = n.GetIntValue(); } },
                { "unit_type", n => { UnitType = n.GetIntValue(); } },
                { "winner", n => { Winner = n.GetObjectValue<global::Opdl.Sdk.Client.Models.Registration>(global::Opdl.Sdk.Client.Models.Registration.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.Registration>("losers", Losers);
            writer.WriteStringValue("resolution_status", ResolutionStatus);
            writer.WriteIntValue("unit_id", UnitId);
            writer.WriteIntValue("unit_type", UnitType);
            writer.WriteObjectValue<global::Opdl.Sdk.Client.Models.Registration>("winner", Winner);
        }
    }
}
#pragma warning restore CS0618
