// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RegistrationRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Optional Master or Slave role advertised by the unit.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>Unit identifier, 0 through 65535.</summary>
        public int? UnitId { get; set; }
        /// <summary>Unit type identifier, 0 through 255.</summary>
        public int? UnitType { get; set; }
        /// <summary>Advertised unit type name. Required and non-blank.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitTypeNameAdvertised { get; set; }
#nullable restore
#else
        public string UnitTypeNameAdvertised { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.RegistrationRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.RegistrationRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.RegistrationRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "role", n => { Role = n.GetStringValue(); } },
                { "unit_id", n => { UnitId = n.GetIntValue(); } },
                { "unit_type", n => { UnitType = n.GetIntValue(); } },
                { "unit_type_name_advertised", n => { UnitTypeNameAdvertised = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("role", Role);
            writer.WriteIntValue("unit_id", UnitId);
            writer.WriteIntValue("unit_type", UnitType);
            writer.WriteStringValue("unit_type_name_advertised", UnitTypeNameAdvertised);
        }
    }
}
#pragma warning restore CS0618
