// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Registration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ip { get; set; }
#nullable restore
#else
        public string Ip { get; set; }
#endif
        /// <summary>The machine property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Machine { get; set; }
#nullable restore
#else
        public string Machine { get; set; }
#endif
        /// <summary>The platform_instances property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Opdl.Sdk.Client.Models.PlatformInstanceRegistrationStatus>? PlatformInstances { get; set; }
#nullable restore
#else
        public List<global::Opdl.Sdk.Client.Models.PlatformInstanceRegistrationStatus> PlatformInstances { get; set; }
#endif
        /// <summary>The reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The role property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The unit_id property</summary>
        public int? UnitId { get; set; }
        /// <summary>The unit_type property</summary>
        public int? UnitType { get; set; }
        /// <summary>The unit_type_name_advertised property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitTypeNameAdvertised { get; set; }
#nullable restore
#else
        public string UnitTypeNameAdvertised { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Opdl.Sdk.Client.Models.Registration"/> and sets the default values.
        /// </summary>
        public Registration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.Registration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.Registration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.Registration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ip", n => { Ip = n.GetStringValue(); } },
                { "machine", n => { Machine = n.GetStringValue(); } },
                { "platform_instances", n => { PlatformInstances = n.GetCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.PlatformInstanceRegistrationStatus>(global::Opdl.Sdk.Client.Models.PlatformInstanceRegistrationStatus.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "unit_id", n => { UnitId = n.GetIntValue(); } },
                { "unit_type", n => { UnitType = n.GetIntValue(); } },
                { "unit_type_name_advertised", n => { UnitTypeNameAdvertised = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ip", Ip);
            writer.WriteStringValue("machine", Machine);
            writer.WriteCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.PlatformInstanceRegistrationStatus>("platform_instances", PlatformInstances);
            writer.WriteStringValue("reason", Reason);
            writer.WriteStringValue("role", Role);
            writer.WriteStringValue("status", Status);
            writer.WriteIntValue("unit_id", UnitId);
            writer.WriteIntValue("unit_type", UnitType);
            writer.WriteStringValue("unit_type_name_advertised", UnitTypeNameAdvertised);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
