// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServiceHealthSummary : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Services whose current observers disagree.</summary>
        public long? Degraded { get; set; }
        /// <summary>Services every current observer found well.</summary>
        public long? Healthy { get; set; }
        /// <summary>Services every current observer found failing.</summary>
        public long? Unhealthy { get; set; }
        /// <summary>Services nothing current says anything about.</summary>
        public long? Unknown { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.ServiceHealthSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.ServiceHealthSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.ServiceHealthSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "degraded", n => { Degraded = n.GetLongValue(); } },
                { "healthy", n => { Healthy = n.GetLongValue(); } },
                { "unhealthy", n => { Unhealthy = n.GetLongValue(); } },
                { "unknown", n => { Unknown = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("degraded", Degraded);
            writer.WriteLongValue("healthy", Healthy);
            writer.WriteLongValue("unhealthy", Unhealthy);
            writer.WriteLongValue("unknown", Unknown);
        }
    }
}
#pragma warning restore CS0618
