// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServiceHealthObservation : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Milliseconds since this report arrived, on the answering instance&apos;s clock.</summary>
        public long? AgeMs { get; set; }
        /// <summary>When the observer says it probed, in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckedAtUtc { get; set; }
#nullable restore
#else
        public string CheckedAtUtc { get; set; }
#endif
        /// <summary>Attempts that had failed in a row when the observer reported.</summary>
        public long? ConsecutiveFailures { get; set; }
        /// <summary>Why the observer&apos;s probe failed, absent when it succeeded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Milliseconds the observer&apos;s probe took.</summary>
        public long? LatencyMs { get; set; }
        /// <summary>Platform instance role that reported: primary or standby.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObserverRole { get; set; }
#nullable restore
#else
        public string ObserverRole { get; set; }
#endif
        /// <summary>When this instance received the report, in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReceivedAtUtc { get; set; }
#nullable restore
#else
        public string ReceivedAtUtc { get; set; }
#endif
        /// <summary>Whether this report has passed the service&apos;s freshness bound.</summary>
        public bool? Stale { get; set; }
        /// <summary>Status this observer reported: Healthy, Unhealthy, or Unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.ServiceHealthObservation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.ServiceHealthObservation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.ServiceHealthObservation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ageMs", n => { AgeMs = n.GetLongValue(); } },
                { "checkedAtUtc", n => { CheckedAtUtc = n.GetStringValue(); } },
                { "consecutiveFailures", n => { ConsecutiveFailures = n.GetLongValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "latencyMs", n => { LatencyMs = n.GetLongValue(); } },
                { "observerRole", n => { ObserverRole = n.GetStringValue(); } },
                { "receivedAtUtc", n => { ReceivedAtUtc = n.GetStringValue(); } },
                { "stale", n => { Stale = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("ageMs", AgeMs);
            writer.WriteStringValue("checkedAtUtc", CheckedAtUtc);
            writer.WriteLongValue("consecutiveFailures", ConsecutiveFailures);
            writer.WriteStringValue("error", Error);
            writer.WriteLongValue("latencyMs", LatencyMs);
            writer.WriteStringValue("observerRole", ObserverRole);
            writer.WriteStringValue("receivedAtUtc", ReceivedAtUtc);
            writer.WriteBoolValue("stale", Stale);
            writer.WriteStringValue("status", Status);
        }
    }
}
#pragma warning restore CS0618
