// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServiceHealthUnit : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Platform instance roles expected to report on this service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExpectedObservers { get; set; }
#nullable restore
#else
        public List<string> ExpectedObservers { get; set; }
#endif
        /// <summary>Machine hosting this service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Machine { get; set; }
#nullable restore
#else
        public string Machine { get; set; }
#endif
        /// <summary>Purpose of the hosting machine.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MachineProfile { get; set; }
#nullable restore
#else
        public string MachineProfile { get; set; }
#endif
        /// <summary>Expected observers that have never reported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MissingObservers { get; set; }
#nullable restore
#else
        public List<string> MissingObservers { get; set; }
#endif
        /// <summary>Last report from each observer, ordered by observer role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Opdl.Sdk.Client.Models.ServiceHealthObservation>? Observations { get; set; }
#nullable restore
#else
        public List<global::Opdl.Sdk.Client.Models.ServiceHealthObservation> Observations { get; set; }
#endif
        /// <summary>Service name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Service { get; set; }
#nullable restore
#else
        public string Service { get; set; }
#endif
        /// <summary>Part this copy plays: master or slave.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceRole { get; set; }
#nullable restore
#else
        public string ServiceRole { get; set; }
#endif
        /// <summary>Expected observers whose last report has expired.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StaleObservers { get; set; }
#nullable restore
#else
        public List<string> StaleObservers { get; set; }
#endif
        /// <summary>Reduced service status: Healthy, Unhealthy, Degraded, or Unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.ServiceHealthUnit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.ServiceHealthUnit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.ServiceHealthUnit();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "expectedObservers", n => { ExpectedObservers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "machine", n => { Machine = n.GetStringValue(); } },
                { "machineProfile", n => { MachineProfile = n.GetStringValue(); } },
                { "missingObservers", n => { MissingObservers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "observations", n => { Observations = n.GetCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.ServiceHealthObservation>(global::Opdl.Sdk.Client.Models.ServiceHealthObservation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "service", n => { Service = n.GetStringValue(); } },
                { "serviceRole", n => { ServiceRole = n.GetStringValue(); } },
                { "staleObservers", n => { StaleObservers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("expectedObservers", ExpectedObservers);
            writer.WriteStringValue("machine", Machine);
            writer.WriteStringValue("machineProfile", MachineProfile);
            writer.WriteCollectionOfPrimitiveValues<string>("missingObservers", MissingObservers);
            writer.WriteCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.ServiceHealthObservation>("observations", Observations);
            writer.WriteStringValue("service", Service);
            writer.WriteStringValue("serviceRole", ServiceRole);
            writer.WriteCollectionOfPrimitiveValues<string>("staleObservers", StaleObservers);
            writer.WriteStringValue("status", Status);
        }
    }
}
#pragma warning restore CS0618
