// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServiceHealthDistribution : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Messages received on the health subject.</summary>
        public long? Delivered { get; set; }
        /// <summary>Decoded reports the view did not apply, by reason.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Opdl.Sdk.Client.Models.ServiceHealthCount>? Dropped { get; set; }
#nullable restore
#else
        public List<global::Opdl.Sdk.Client.Models.ServiceHealthCount> Dropped { get; set; }
#endif
        /// <summary>Observations from this instance that reached the connection.</summary>
        public long? Published { get; set; }
        /// <summary>Observations the connection refused.</summary>
        public long? PublishFailed { get; set; }
        /// <summary>Messages rejected before decoding, by reason.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Opdl.Sdk.Client.Models.ServiceHealthCount>? Rejected { get; set; }
#nullable restore
#else
        public List<global::Opdl.Sdk.Client.Models.ServiceHealthCount> Rejected { get; set; }
#endif
        /// <summary>Whether expected remote observations are arriving: Connected, Partial, Isolated, or Local.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Observations replaced by a newer one before being sent.</summary>
        public long? Superseded { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.ServiceHealthDistribution"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.ServiceHealthDistribution CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.ServiceHealthDistribution();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "delivered", n => { Delivered = n.GetLongValue(); } },
                { "dropped", n => { Dropped = n.GetCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.ServiceHealthCount>(global::Opdl.Sdk.Client.Models.ServiceHealthCount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "publishFailed", n => { PublishFailed = n.GetLongValue(); } },
                { "published", n => { Published = n.GetLongValue(); } },
                { "rejected", n => { Rejected = n.GetCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.ServiceHealthCount>(global::Opdl.Sdk.Client.Models.ServiceHealthCount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "superseded", n => { Superseded = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("delivered", Delivered);
            writer.WriteCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.ServiceHealthCount>("dropped", Dropped);
            writer.WriteLongValue("published", Published);
            writer.WriteLongValue("publishFailed", PublishFailed);
            writer.WriteCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.ServiceHealthCount>("rejected", Rejected);
            writer.WriteStringValue("state", State);
            writer.WriteLongValue("superseded", Superseded);
        }
    }
}
#pragma warning restore CS0618
