// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Opdl.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServiceHealthResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The distribution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Opdl.Sdk.Client.Models.ServiceHealthDistribution? Distribution { get; set; }
#nullable restore
#else
        public global::Opdl.Sdk.Client.Models.ServiceHealthDistribution Distribution { get; set; }
#endif
        /// <summary>Environment this view covers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Environment { get; set; }
#nullable restore
#else
        public string Environment { get; set; }
#endif
        /// <summary>When this snapshot was taken, in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneratedAtUtc { get; set; }
#nullable restore
#else
        public string GeneratedAtUtc { get; set; }
#endif
        /// <summary>Machine of the instance that produced this view.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Machine { get; set; }
#nullable restore
#else
        public string Machine { get; set; }
#endif
        /// <summary>Project this view covers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Project { get; set; }
#nullable restore
#else
        public string Project { get; set; }
#endif
        /// <summary>Fixed instance role that produced this view: primary or standby.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>Every service at this site, in inventory order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Opdl.Sdk.Client.Models.ServiceHealthUnit>? Services { get; set; }
#nullable restore
#else
        public List<global::Opdl.Sdk.Client.Models.ServiceHealthUnit> Services { get; set; }
#endif
        /// <summary>Site this view covers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Site { get; set; }
#nullable restore
#else
        public string Site { get; set; }
#endif
        /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Opdl.Sdk.Client.Models.ServiceHealthSummary? Summary { get; set; }
#nullable restore
#else
        public global::Opdl.Sdk.Client.Models.ServiceHealthSummary Summary { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.ServiceHealthResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Opdl.Sdk.Client.Models.ServiceHealthResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Opdl.Sdk.Client.Models.ServiceHealthResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "distribution", n => { Distribution = n.GetObjectValue<global::Opdl.Sdk.Client.Models.ServiceHealthDistribution>(global::Opdl.Sdk.Client.Models.ServiceHealthDistribution.CreateFromDiscriminatorValue); } },
                { "environment", n => { Environment = n.GetStringValue(); } },
                { "generatedAtUtc", n => { GeneratedAtUtc = n.GetStringValue(); } },
                { "machine", n => { Machine = n.GetStringValue(); } },
                { "project", n => { Project = n.GetStringValue(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "services", n => { Services = n.GetCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.ServiceHealthUnit>(global::Opdl.Sdk.Client.Models.ServiceHealthUnit.CreateFromDiscriminatorValue)?.AsList(); } },
                { "site", n => { Site = n.GetStringValue(); } },
                { "summary", n => { Summary = n.GetObjectValue<global::Opdl.Sdk.Client.Models.ServiceHealthSummary>(global::Opdl.Sdk.Client.Models.ServiceHealthSummary.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Opdl.Sdk.Client.Models.ServiceHealthDistribution>("distribution", Distribution);
            writer.WriteStringValue("environment", Environment);
            writer.WriteStringValue("generatedAtUtc", GeneratedAtUtc);
            writer.WriteStringValue("machine", Machine);
            writer.WriteStringValue("project", Project);
            writer.WriteStringValue("role", Role);
            writer.WriteCollectionOfObjectValues<global::Opdl.Sdk.Client.Models.ServiceHealthUnit>("services", Services);
            writer.WriteStringValue("site", Site);
            writer.WriteObjectValue<global::Opdl.Sdk.Client.Models.ServiceHealthSummary>("summary", Summary);
        }
    }
}
#pragma warning restore CS0618
