// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Opdl.Sdk.Client.Registrations.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Opdl.Sdk.Client.Registrations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \registrations\{unit_type}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUnit_typeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Opdl.Sdk.Client.registrations.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Registrations.Item.Item.WithUnit_ItemRequestBuilder"/></returns>
        public global::Opdl.Sdk.Client.Registrations.Item.Item.WithUnit_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("unit_id", position);
                return new global::Opdl.Sdk.Client.Registrations.Item.Item.WithUnit_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Opdl.Sdk.Client.registrations.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Registrations.Item.Item.WithUnit_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Opdl.Sdk.Client.Registrations.Item.Item.WithUnit_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("unit_id", position);
                return new global::Opdl.Sdk.Client.Registrations.Item.Item.WithUnit_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Opdl.Sdk.Client.Registrations.Item.WithUnit_typeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUnit_typeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registrations/{unit_type}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Opdl.Sdk.Client.Registrations.Item.WithUnit_typeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUnit_typeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registrations/{unit_type}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
