version: 3

workdir: .

allow:
  depOnAnyVendor: false
  deepScan: true

exclude:
  - ".gocache"
  - ".lintcache"
  - ".test-results"

excludeFiles:
  - "^.*_test\\.go$"

vendors:
  toml: { in: "github.com/BurntSushi/toml**" }
  nats-server: { in: "github.com/nats-io/nats-server/v2/**" }
  nats-client: { in: "github.com/nats-io/nats.go**" }
  sys: { in: "golang.org/x/sys/**" }

components:
  api: { in: api }
  cmd: { in: cmd }
  deployment: { in: deployment }
  embedded: { in: embedded }
  app: { in: internal/app }
  config: { in: internal/config }
  events: { in: internal/events }
  eventfabric: { in: internal/eventfabric }
  eventfabric-nats: { in: internal/eventfabric/nats }
  httpapi: { in: internal/httpapi }
  redundancy: { in: internal/redundancy }
  registration: { in: internal/registration }

deps:
  cmd:
    mayDependOn: [app]
  embedded:
    mayDependOn: [deployment]
  app:
    mayDependOn: [config, deployment, eventfabric, eventfabric-nats, httpapi, redundancy, registration]
  redundancy:
    canUse: [sys]
  config:
    canUse: [toml]
    mayDependOn: [deployment, embedded]
  events:
    mayDependOn: [deployment]
  eventfabric:
    mayDependOn: [events]
  eventfabric-nats:
    canUse: [nats-server, nats-client]
    mayDependOn: [deployment, events, eventfabric]
  httpapi:
    mayDependOn: [api, registration]
  registration:
    mayDependOn: [api, events, eventfabric]
