// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Opdl.Sdk.Client.Models;
using Opdl.Sdk.Client.Registrations.Conflicts;
using Opdl.Sdk.Client.Registrations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Opdl.Sdk.Client.Registrations
{
    /// <summary>
    /// Builds and executes requests for operations under \registrations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RegistrationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The conflicts property</summary>
        public global::Opdl.Sdk.Client.Registrations.Conflicts.ConflictsRequestBuilder Conflicts
        {
            get => new global::Opdl.Sdk.Client.Registrations.Conflicts.ConflictsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Opdl.Sdk.Client.registrations.item collection</summary>
        /// <param name="position">Opaque proposal identifier returned by registerUnit.</param>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Registrations.Item.WithProposal_ItemRequestBuilder"/></returns>
        public global::Opdl.Sdk.Client.Registrations.Item.WithProposal_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("proposal_id", position);
                return new global::Opdl.Sdk.Client.Registrations.Item.WithProposal_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Opdl.Sdk.Client.Registrations.RegistrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistrationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registrations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Opdl.Sdk.Client.Registrations.RegistrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistrationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registrations", rawUrl)
        {
        }
        /// <summary>
        /// List registration proposals
        /// </summary>
        /// <returns>A List&lt;global::Opdl.Sdk.Client.Models.Registration&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Opdl.Sdk.Client.Models.ErrorModel">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Opdl.Sdk.Client.Models.Registration>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Opdl.Sdk.Client.Models.Registration>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Opdl.Sdk.Client.Models.ErrorModel.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Opdl.Sdk.Client.Models.Registration>(requestInfo, global::Opdl.Sdk.Client.Models.Registration.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Propose a unit registration
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Models.ProposalAccepted"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Opdl.Sdk.Client.Models.ErrorModel">When receiving a 400 status code</exception>
        /// <exception cref="global::Opdl.Sdk.Client.Models.ErrorModel">When receiving a 422 status code</exception>
        /// <exception cref="global::Opdl.Sdk.Client.Models.ErrorModel">When receiving a 500 status code</exception>
        /// <exception cref="global::Opdl.Sdk.Client.Models.ErrorModel">When receiving a 501 status code</exception>
        /// <exception cref="global::Opdl.Sdk.Client.Models.ErrorModel">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Opdl.Sdk.Client.Models.ProposalAccepted?> PostAsync(global::Opdl.Sdk.Client.Models.RegistrationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Opdl.Sdk.Client.Models.ProposalAccepted> PostAsync(global::Opdl.Sdk.Client.Models.RegistrationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Opdl.Sdk.Client.Models.ErrorModel.CreateFromDiscriminatorValue },
                { "422", global::Opdl.Sdk.Client.Models.ErrorModel.CreateFromDiscriminatorValue },
                { "500", global::Opdl.Sdk.Client.Models.ErrorModel.CreateFromDiscriminatorValue },
                { "501", global::Opdl.Sdk.Client.Models.ErrorModel.CreateFromDiscriminatorValue },
                { "503", global::Opdl.Sdk.Client.Models.ErrorModel.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Opdl.Sdk.Client.Models.ProposalAccepted>(requestInfo, global::Opdl.Sdk.Client.Models.ProposalAccepted.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List registration proposals
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Propose a unit registration
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Opdl.Sdk.Client.Models.RegistrationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Opdl.Sdk.Client.Models.RegistrationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Opdl.Sdk.Client.Registrations.RegistrationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Opdl.Sdk.Client.Registrations.RegistrationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Opdl.Sdk.Client.Registrations.RegistrationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RegistrationsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RegistrationsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
